# Generated by Django 5.1.4 on 2025-01-07 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizattempt_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
