# Generated by Django 5.1.4 on 2025-01-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizattempt_answers_alter_quizattempt_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
